import type { Metadata } from "next";
import "../globals.css";
import AuthProvider from "@/context/AuthProvier";
import { Toaster } from "@/components/ui/toaster";
import React from "react";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
        <AuthProvider>
      <body className={` antialiased`}>
      {children}
      <Toaster />
      </body></AuthProvider>
    </html>
  );
}
