import type { Metadata } from "next";
<<<<<<< HEAD
import { Inter } from "next/font/google";
import '@/app/globals.css';
import React from "react";
import { Toaster } from "@/components/ui/toaster";
import { ThemeProvider } from "@/components/theme-provider";
=======
import { Inter } from "next/font/google";  
import '@/app/globals.css'; 
import React from "react";
import { Toaster } from "@/components/ui/toaster";
>>>>>>> 2ff8f5608bc6b6464652c83742421df2e92380cc

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
<<<<<<< HEAD
  title: "ShadowTalk",
=======
  title: "Mystery Message",
>>>>>>> 2ff8f5608bc6b6464652c83742421df2e92380cc
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
<<<<<<< HEAD
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
        <Toaster />
=======
          {children}
          <Toaster />
>>>>>>> 2ff8f5608bc6b6464652c83742421df2e92380cc

      </body>
    </html>
  );
}